### ISSUE TITLE
No versions available for embedded-browser-react?

### ISSUE THREAD

**Issue by magikarp28** [msv300/embedded-browser-react#14]
Has this library been removed? npm install embedded-browser-react returns error "No versions available for embedded-browser-react"

**Comment by m-sakthi** [comment]
It is available now.

**Comment by Iven2132** [comment]
@m-sakthi The issue is still their "npm ERR! No versions available for embedded-browser-react" Any fix?

**Comment by m-sakthi** [comment]
> Iven2132

Just tried installing this package. It works. 
<img width="767" alt="image" src="https://github.com/m-sakthi/embedded-browser-react/assets/22537093/b224008a-f683-4078-9b36-c30bce963ffb">

**Comment by Iven2132** [comment]
@m-sakthi Yeah, The issue is with readme it's npm install embedded-browser-react instead of npm install embedded-react-browser

**Comment by Iven2132** [comment]
@m-sakthi Also it's giving me an error SecurityError: Failed to read a named property 'href' from 'Location': Blocked a frame with origin ["http://localhost:3000"](http://localhost:3000/%22http://localhost:3000%22) from accessing a cross-origin frame. 

I tried with the StackOverflow website.

**Comment by m-sakthi** [comment]
It is because the browser blocks cross-origin resources. Both the iframe href url and the actual host has to be the same it you understand cross-origin policy of the browser.

**Comment by Iven2132** [comment]
@m-sakthi But this problem can be solved by a proxy server? Also, does it handle URL routing?
